// build-host 防回归：产物 host.js 里的跨包依赖必须是「外部化裸说明符」，而不是被内联。
//
// 为什么值得一条测试（两个坏方向都不报错、只在线上发作）：发布形态下 host.js 躺在
// node_modules 里被 dsh 载入——
//   1) 内联：`@jayyuen666/dsh-plugin-shared/lib/*` 一旦被打进产物，shared 的模块级状态就在每个插件
//      里各复制一份；rolldown 的 external 字符串项是精确匹配，只列包名会漏掉**子路径**，
//      故 build-host.mjs 按「包名段」判定（该坑已在脚本注释登记）。
//   2) 残留：产物里只要还剩 `./lib/xxx.ts`，Node 载入即抛 ERR_UNSUPPORTED_NODE_MODULES_
//      TYPE_STRIPPING；而 dependencies 里跑掉一个包（如 schemastery 退回 devDependencies）
//      就会被整包内联——体积翻倍正是内联发生了的指纹，故一并钉住。
import { describe, it } from "vitest";
import assert from "node:assert/strict";
import { buildHost } from "../build-host.mjs";
import { hostFreshnessEvidence } from "./host-freshness.ts";

describe("buildHost()", () => {
  it("host.js 与最新构建逐字节一致（改 host.ts / lib/*.ts 后必须 node build-host.mjs）", async () => {
    const { pkgName, pkgDir, onDisk, built } = await hostFreshnessEvidence(import.meta.url);
    assert.equal(
      onDisk,
      built,
      onDisk === built
        ? "fresh"
        : `[${pkgName}] host.js 已过期：host.ts（或其依赖）变更后未重建。请运行：cd ${pkgDir} && node build-host.mjs`,
    );
  });

  it("产物 host.js：运行期跨包依赖保持 external（未内联）", async () => {
    const out = await buildHost();
    assert.ok(
      out.startsWith("// GENERATED by build-host.mjs"),
      "产物须带生成标记（勿手改 host.js）",
    );
    // 值导入的包必须列在 dependencies，否则被内联
    assert.ok(
      out.includes('from "@deepseek-ai/schemastery"'),
      "宿主 fork 的 schemastery 必须外部化（0.1.7 的 volatile 字段解析只有它有实现）",
    );
    // 反向锁：不得退回公共 schemastery——它没有 .volatile()，volatile 字段解析出的仍是
    // 普通值，设置卡写进去的值永远读不到（0.1.7 迁移的根因）。
    assert.ok(
      !/from\s+["']schemastery["']/u.test(out),
      "产物不得再值导入公共 schemastery（volatile 解析只在宿主 fork 里）",
    );
    // 子路径说明符：external 字符串项匹配不到的那个坑
    assert.ok(
      out.includes('from "@jayyuen666/dsh-plugin-shared/lib/tool-events"'),
      "shared/tool-events 必须外部化",
    );
    assert.ok(
      out.includes('from "@jayyuen666/dsh-plugin-shared/lib/project-key"'),
      "shared/project-key 必须外部化（lib/gateway-target.ts 的 project 单源，内联会让网关反馈与 lesson 总线各算一份键）",
    );
    assert.ok(
      out.includes('from "@jayyuen666/dsh-plugin-shared/lib/locale"'),
      "shared/locale 必须外部化（host 侧文案语言与官方 locale 偏好同源，内联会把 resolveLocale 复制进每个插件）",
    );
    assert.ok(
      out.includes('from "@deepseek-ai/dsh-credentials"'),
      "dsh-credentials 必须外部化（口径 A：值导入落 dependencies）",
    );
    assert.ok(
      !/^function (?:credentialRef|isCredentialRefName|brandString|brandNumber)\(/mu.test(out),
      "产物不得内联官方 branded-string 构造器（出现函数体=依赖又落回 devDependencies）",
    );
    assert.ok(
      out.includes('from "@jayyuen666/dsh-plugin-shared/lib/record"'),
      "shared/record 必须外部化（SP-D 起 isRecord/fieldOf 单点在 shared；本包那份异形 messageOf 仍留本地）",
    );
  });

  it("产物 host.js：不残留 ./x.ts 形态的相对说明符", async () => {
    const out = await buildHost();
    // lib/*.ts 应已被吃进单文件；留着即"发布后 Node 直接拒载"的形态
    assert.ok(!/["']\.\/[^"']*\.ts["']/u.test(out), "不得有 ./x.ts 说明符残留");
  });
});
