#!/usr/bin/env node
/// <reference types="node" />
// 构建 client.js：rolldown 把 src/client-entry.ts + lib/embedding-catalog.ts
// 打包为 CJS（react 外部化），再包进 window.__ModuleLoader__.load({ id, factory })
// UMD 外壳。id 取 package.json 的 name，与 dsh.client 模块表键一致。
// 运行：node build-client.mjs（或 pnpm run build:client）。buildClient() 供测试导入。
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { rolldown } from "rolldown";
import { canonicalizeRegionPaths } from "@jayyuen66/dsh-plugin-shared/lib/canonicalize-region-paths";

const root = import.meta.dirname;

/** package.json 的 name（id 用，与产物/模块表对齐）。 */
function pkgNameOf() {
  // 这里（及下面的 rolldown/writeFileSync）曾挂 5 条 `oxlint-disable` 豁免 typescript/no-unsafe-*，
  // 实测是死重量：本文件整个不进 lint —— 基线 ignorePatterns 点名 `build-client.mjs`
  // （`npx oxlint build-client.mjs` ⇒ "No files found to lint"，0 files）；`*.mjs` 上这一族也已被
  // SCRIPTS_OVERRIDES 关掉。对照实测：被 lint 的文件里给一条**已关**的规则挂豁免，
  // reportUnusedDisableDirectives 仍报 "Unused oxlint-disable directive" ⇒ 规则不在场并不会
  // 让豁免静默通过，只有"文件被整个排除"会。故 5 条已删。下面两行是代码自身的事实：
  // .mjs 无 TS 标注 ⇒ readFileSync/JSON.parse 的返回值在类型面上是隐式 any，注解在这里也不合法。
  const parsed = readFileSync(path.join(root, "package.json"), "utf8");
  const parsedJson = JSON.parse(parsed);
  // name 取字段后立刻用 typeof 收窄，非空字符串才是可用的 id。
  const { name } = parsedJson;
  if (typeof name !== "string" || name === "") {
    throw new Error("package.json 缺少非空 name 字段");
  }
  return name;
}

const pkgName = pkgNameOf();

/** 生成 client.js 的完整文本（含 ModuleLoader 外壳）。 */
export async function buildClient() {
  const bundle = await rolldown({
    input: path.join(root, "src", "client-entry.ts"),
    external: ["react"],
    platform: "browser",
    resolve: {
      extensions: [".ts", ".mjs", ".js", ".json"],
    },
  });
  const { output } = await bundle.generate({
    format: "cjs",
  });
  const chunk = output.find((item) => item.type === "chunk");
  if (chunk === undefined) {
    throw new Error("rolldown generate returned no chunk output");
  }
  // 见 shared/lib/canonicalize-region-paths.ts：`//#region` 行的路径由 rolldown 按 process.cwd()
  // 算出 ⇒ 同一份源码两种字节。折 canonical 必须落在返回值之前（test/client-freshness.ts 逐字节
  // 比内存构建与磁盘产物），不能只在 writeFileSync 那一侧做。
  const body = canonicalizeRegionPaths(chunk.code.trimEnd(), root);
  return [
    "// GENERATED by buildClient() in build-client.mjs — edit src/client-entry.ts, then run `node build-client.mjs`.",
    "window.__ModuleLoader__.load({",
    `  id: '${pkgName}',`,
    "  factory: (require) => {",
    "    var module = { exports: {} };",
    "    var exports = module.exports;",
    body,
    "    return module.exports;",
    "  },",
    "});",
    "",
  ].join("\n");
}

async function main() {
  const out = await buildClient();
  writeFileSync(path.join(root, "client.js"), out, "utf8");
  console.info("client.js written:", out.length, "chars");
}

if (process.argv[1] === import.meta.filename) {
  try {
    await main();
  } catch (error) {
    console.error(error);
    process.exitCode = 1;
  }
}
